---
# Source: zalando-postgres/charts/pgadmin4/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mypg-pgadmin4
  namespace: "zalando-db"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mypg
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "9.8"
    helm.sh/chart: pgadmin4-1.50.0
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pgadmin4
      app.kubernetes.io/instance: mypg
  ingress:
  - ports:
    - port: 80
---
# Source: zalando-postgres/charts/pgadmin4/templates/auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mypg-pgadmin4
  namespace: "zalando-db"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mypg
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "9.8"
    helm.sh/chart: pgadmin4-1.50.0
type: Opaque
data:
  password: "YWRtaW4="
---
# Source: zalando-postgres/templates/pgadmin-servers-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: zalando-db
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "mypg",
          "Group": "Servers",
          "Host": "mypg",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "require"
        }
      }
    }
---
# Source: zalando-postgres/charts/pgadmin4/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypg-pgadmin4
  namespace: "zalando-db"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mypg
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "9.8"
    helm.sh/chart: pgadmin4-1.50.0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Source: zalando-postgres/charts/pgadmin4/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mypg-pgadmin4
  namespace: "zalando-db"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mypg
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "9.8"
    helm.sh/chart: pgadmin4-1.50.0
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/instance: mypg
---
# Source: zalando-postgres/charts/pgadmin4/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypg-pgadmin4
  namespace: "zalando-db"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mypg
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "9.8"
    helm.sh/chart: pgadmin4-1.50.0
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin4
      app.kubernetes.io/instance: mypg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin4
        app.kubernetes.io/instance: mypg
      annotations:
        checksum/secret: b69042d110425590931d0b32441bd6422ae6fb50ba1e82db1de3c29da36e1edb
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pgadmin4
          image: "docker.io/dpage/pgadmin4:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /misc/ping
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              port: http
              path: /misc/ping
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: http
              path: /misc/ping
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "False"
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mypg-pgadmin4
                  key: password
            - name: PGADMIN_SERVER_JSON_FILE
              value: /pgadmin4/servers.json
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
              subPath: ""
            - name: definitions
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          resources:
            {}
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: mypg-pgadmin4
        - name: definitions
          configMap:
            name: pgadmin-servers
            items:
            - key: servers.json
              path: servers.json
      securityContext:
        fsGroup: 5050
        runAsGroup: 5050
        runAsUser: 5050
---
# Source: zalando-postgres/templates/postgres.yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: mypg
  namespace: zalando-db
spec:
  teamId: devops

  dockerImage: ghcr.io/zalando/spilo-17:4.0-p2
  numberOfInstances: 2

  volume:
    size: 1Gi

  postgresql:
    version: "17"

  # -----------------------------
  # USERS
  # -----------------------------
  users:
    app_user:
      - superuser
      - createdb

  # -----------------------------
  # DATABASES
  # -----------------------------
  databases:
    appdb: app_user

  # -----------------------------
  # CONNECTION POOLER
  # -----------------------------
  enableConnectionPooler: true

  # -----------------------------
  # LOGICAL BACKUP (Operator CronJob)
  # -----------------------------
  enableLogicalBackup: true
  logicalBackupSchedule: "0 * * * *"

  # -----------------------------
  # PHYSICAL BACKUP (WAL-G)
  # IMPORTANT:
  # Zalando expects env directly under spec.env
  # -----------------------------
---
# Source: zalando-postgres/charts/pgadmin4/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "mypg-pgadmin4-test-connection"
  namespace: "zalando-db"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: mypg
    app.kubernetes.io/name: pgadmin4
    app.kubernetes.io/version: "9.8"
    helm.sh/chart: pgadmin4-1.50.0
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 5051
    runAsGroup: 5051
    runAsUser: 5051
  containers:
    - name: wget
      image: "docker.io/busybox:latest"
      env:
        - name: PGADMIN_HOST
          value: mypg-pgadmin4
        - name: PGADMIN_PORT
          value: "80"
      command:
        - /bin/sh
        - -ec
        - |
          response=$(wget -qSO - http://${PGADMIN_HOST}:${PGADMIN_PORT} 2>&1)
          check=$(echo $response | grep -c '200 OK'); echo $check; if [[ $check -gt 0 ]]; then echo "Response OK"; else exit 1; fi
      resources:
        {}
      securityContext:
        readOnlyRootFilesystem: true
  restartPolicy: Never
